spring.application.name=back

# Permite levantar sin exportar .env (usa estos valores por defecto si no hay variables de entorno)
server.port=${PORT:6789}
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-polished-band-acvrt1m0-pooler.sa-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_9S2vxOtCweTu&sslmode=require&channelBinding=require}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
