spring.application.name=back

# Configuracion fija solicitada para conexion a PostgreSQL
server.port=${PORT:6789}
spring.datasource.url=jdbc:postgresql://localhost:5432/demo01
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
