spring.application.name=back
server.port=${PORT:6789}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/clinica_dental}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
